safe_emails = [
    "Hi Sarah, just checking if we're still on for lunch tomorrow? I was thinking that new Italian place downtown. Let me know!",
    "The quarterly budget meeting is scheduled for May 15th at 2:00 PM in Conference Room B. Please bring your department's Q2 forecasts.",
    "Your order #23875 has been shipped and will arrive on Wednesday. Track your package here: http://legitimatestore.com/track.",
    "Thank you for your application to University of California. We are reviewing your materials and will respond within 3-4 weeks.",
    "Reminder: The company picnic is this Saturday from 12-4pm at Lakeside Park. Families welcome. Please RSVP by tomorrow.",
    "John, can you send me the final version of the presentation for tomorrow's client meeting? Thanks.",
    "Your monthly newsletter from Green Gardens - This month's topics: Summer planting tips, pest control, and our annual sale next weekend.",
    "Dear Mr. Thompson, Thank you for your recent stay at Hilton Hotel. We'd appreciate your feedback in this short survey.",
    "The books you requested are now available for pickup at the main library desk. They will be held until May 22nd.",
    "Your flight confirmation: UA823 departing SFO 10:45AM arriving JFK 7:15PM on June 5th. Check-in opens 24hrs before departure.",
    "Hi team, I've uploaded the project files to our shared drive. Please review the documentation before Friday's meeting.",
    "Your prescription for Amoxicillin is ready for pickup at Walgreens on Main Street. Pharmacy hours: 9am-9pm.",
    "This is a reminder that your dentist appointment is scheduled for tomorrow at 3:30pm with Dr. Martinez.",
    "Hello participants, The webinar 'Professional Development in Tech Industries' will begin tomorrow at 1pm EST. Link to join was sent in a previous email.",
    "Your energy bill is now available. Amount due: $78.45. Due date: May 15. Log in to your account to view usage details.",
    "The office will be closed on Monday, May 29th in observance of Memorial Day. Regular hours will resume on Tuesday.",
    "Thank you for your donation to Red Cross Disaster Relief. Your contribution of $50 will help families affected by recent flooding.",
    "Your car service is scheduled for tomorrow at 9:00 AM at Joe's Auto Shop. Please bring your vehicle registration.",
    "Hi Jessica, I've reviewed your proposal and have some suggestions. Can we meet tomorrow afternoon to discuss?",
    "The building will undergo maintenance this weekend. Water will be shut off from 10am-2pm on Saturday.",
    "Your tax documents for 2023 are now available in your online account. Please access them by April 15 for filing.",
    "Hello participants, thank you for attending yesterday's workshop. As promised, here are the slides and additional resources.",
    "Your library books are due in 3 days. Return or renew online at library.org to avoid late fees.",
    "This is a confirmation that your vacation time request (June 10-15) has been approved. Enjoy your time off!",
    "Hi Ryan, could you cover my shift on Friday evening? I have a family emergency. I'll be happy to take your Sunday shift in return.",
    "Your monthly account statement is ready. No unusual activity detected. Log in to view details.",
    "The school board meeting has been rescheduled to next Thursday at 7pm in the auditorium. Public comments welcome.",
    "Just checking if you received the contract I sent last week? We need your signature by Friday to proceed.",
    "Your order from Fresh Groceries will be delivered today between 2-4pm. Please ensure someone is available to receive it.",
    "Congratulations on your work anniversary! It's been 5 years since you joined our team, and we appreciate your contributions.",
    "This is a friendly reminder that rent is due on the 1st of the month. You can pay online or drop a check at the office.",
    "The gym will be closed from 9pm-5am tonight for routine maintenance. We apologize for any inconvenience.",
    "Dear valued customer, thank you for your recent purchase. Please allow 3-5 business days for delivery.",
    "Your pet's annual vaccination is due this month. Please call our office to schedule an appointment.",
    "Team update: We've successfully launched the new website. Thank you all for your hard work on this project.",
    "Your subscription to The New York Times will renew automatically on June 1. Your card ending in 4832 will be charged $15.99.",
    "The neighborhood watch meeting is scheduled for Wednesday at 7pm at the community center. New members welcome.",
    "Thank you for registering for our upcoming conference. Check-in begins at 8:30am on May 20th.",
    "Your insurance policy is up for renewal next month. No action is needed; it will renew automatically.",
    "Hello, this is a reminder about our book club meeting tomorrow at 7pm. We'll be discussing 'The Great Gatsby'.",
    "Your appointment with Dr. Johnson has been confirmed for Tuesday at 10:30am. Please arrive 15 minutes early.",
    "The company holiday party will be held on December 18th at The Grand Hotel. Please RSVP by December 1st.",
    "Your child's school will have an early dismissal at 12:30pm on Friday due to teacher development.",
    "This is to confirm your reservation at Seaside Restaurant for Saturday at 7:30pm for a party of 4.",
    "Thank you for your payment of $1,250 for Invoice #12345. Your account is now current.",
    "The building fire alarm testing will take place on Tuesday morning between 10-11am. No evacuation necessary.",
    "Your membership to the fitness center has been renewed. Your new card is available at the front desk.",
    "Just wanted to thank you for your referral of John Smith. We're excited to have him join our team next month.",
    "Your water bill is slightly higher than usual this month. We've included tips for conservation in this email.",
    "Hi Dave, do you have the quarterly sales figures? I need to include them in my presentation for tomorrow."
]

malicious_emails = [
    "URGENT: Your account has been compromised! Verify your identity immediately: http://banking-secure-verify.com",
    "Your Amazon order #39572 has been processed. Click here to track your package: http://amaz0n-tracking-secure.net",
    "WARNING: Your PayPal account will be suspended in 24 hours. Verify your information: http://payp@l-secure.com",
    "You've won a $1000 Walmart gift card! Claim now: http://free-walmart-gifts.com. Offer expires in 24 hours!",
    "Your Netflix subscription payment failed. Update your billing information immediately: http://netflix-accounts-billing.com",
    "IRS TAX REFUND: You are eligible for an additional $4,829.00 refund. Submit your details: http://irs-refund-gov.org",
    "Your Apple ID was used to sign in on a new device. If this wasn't you, recover your account: http://apple-id-verify.net",
    "Bank of America: Your online access has been temporarily disabled. Restore access: http://bofa-secure-login.com",
    "ATTENTION: Your Social Security Number has been suspended due to suspicious activity. Call immediately: 1-888-555-1234",
    "Microsoft Security Alert: Your email account shows unusual sign-in activity. Verify your identity: http://microsoft-verify.net",
    "Your package could not be delivered due to incorrect address. Reschedule delivery: http://usps-delivery-reschedule.com",
    "Your credit card has been charged $499 for iPhone 15 purchase. If this wasn't you, dispute here: http://billing-dispute-form.com",
    "FINAL NOTICE: Your vehicle warranty is about to expire. Extend coverage at 50% discount: http://auto-warranty-extension.com",
    "Facebook Security: Your account was recently logged into from an unrecognized location. Verify it's you: http://facebook-secure-login.net",
    "We detected a virus on your computer. Remove it immediately by downloading our security tool: http://free-antivirus-check.com",
    "Congratulations! Your email was selected to receive a special Bitcoin investment opportunity. Get started now: http://bitcoin-profit-boost.com",
    "Your bank account is at risk! Secure it now before unauthorized access: http://secure-your-bank.com",
    "Amazon Prime membership renewal required! Update your payment details to avoid cancellation: http://amazon-prime-renew.com",
    "Your tax return contains errors. Avoid penalties by verifying your submission: http://irs-tax-filing-check.com",
    "Someone attempted to log into your email account. Secure it now: http://email-security-login.com",
    "WIN A FREE iPhone 14! Enter now before the contest closes: http://free-iphone14-giveaway.com",
    "Your mobile service will be disconnected due to unpaid bills. Pay now: http://verizon-billing-issues.com",
    "Security Alert: A new device signed into your Google account. If this wasn’t you, secure your account now: http://google-security-alert.com",
    "Your business listing on Google Maps is at risk of removal. Confirm your details: http://google-business-verify.com",
    "Claim your exclusive crypto trading bonus now! Start earning instantly: http://crypto-trade-fast.com",
    "You have received a confidential message from HR. Click here to view: http://secure-hr-documents.com",
    "FINAL ATTEMPT: Your account password is about to expire. Reset it now: http://password-reset-now.com",
    "Your driver's license information has been flagged for suspicious activity. Verify immediately: http://dmv-security-check.com",
    "You've been selected for a government grant of $10,000! Claim your funds here: http://gov-grant-apply.com",
    "Your Chase account requires verification. Log in now: http://chase-secure-login.com",
    "A friend tagged you in a viral video. Watch it now: http://facebook-video-link.com",
    "Dear customer, your tax refund check is ready for deposit. Confirm details: http://bank-refund-verify.com",
    "Your hotel booking has been canceled due to payment failure. Reconfirm now: http://hotel-reservation-check.com",
    "Unusual activity detected on your eBay account. Verify recent transactions: http://ebay-security-check.com",
    "Final warning: Your LinkedIn account is at risk of suspension. Confirm your identity now: http://linkedin-security-check.com",
    "Your Microsoft Office subscription has expired. Renew now to avoid service disruption: http://microsoft-office-renew.com",
    "We have a job opportunity for you! Earn $5,000 per week from home: http://work-from-home-offer.com",
    "Suspicious withdrawals detected on your Wells Fargo account. Review activity: http://wellsfargo-secure-alert.com",
    "The FBI has flagged your IP address for illegal activity. Resolve now: http://fbi-cybersecurity-alert.com",
    "Your credit score has changed! Check your updated score now: http://credit-score-update.com",
    "Your voter registration status is inactive. Reactivate now: http://voter-registration-check.com",
    "Your package delivery requires additional payment. Pay now: http://dhl-delivery-fee.com",
    "We have detected a security breach on your device. Fix it now: http://malware-scan-immediate.com",
    "Your bank statement is now available. Download it here: http://bank-statement-download.com",
    "Your car loan has been approved! Claim your funds now: http://auto-loan-offer.com",
    "Urgent: Your Amazon Prime trial is expiring. Upgrade now: http://amazon-trial-upgrade.com",
    "Your student loan repayment plan has been adjusted. Review the new terms: http://student-loan-check.com",
    "Your email storage is full. Upgrade now to avoid losing emails: http://email-storage-upgrade.com",
    "Confirm your shipping address to receive your pending refund: http://refund-verify.com"
]

all_emails = safe_emails + malicious_emails