synthetic_labeld_emails = {
    # SAFE
    "Hi Sarah, just checking if we're still on for lunch tomorrow? I was thinking that new Italian place downtown. Let me know!" :"safe",
    "The quarterly budget meeting is scheduled for May 15th at 2:00 PM in Conference Room B. Please bring your department's Q2 forecasts." :"safe",
    "Your order #23875 has been shipped and will arrive on Wednesday. Track your package here: http://legitimatestore.com/track." :"safe",
    "Thank you for your application to University of California. We are reviewing your materials and will respond within 3-4 weeks." :"safe",
    "Reminder: The company picnic is this Saturday from 12-4pm at Lakeside Park. Families welcome. Please RSVP by tomorrow." :"safe",
    "John, can you send me the final version of the presentation for tomorrow's client meeting? Thanks." :"safe",
    "Your monthly newsletter from Green Gardens - This month's topics: Summer planting tips, pest control, and our annual sale next weekend." :"safe",
    "Dear Mr. Thompson, Thank you for your recent stay at Hilton Hotel. We'd appreciate your feedback in this short survey." :"safe",
    "The books you requested are now available for pickup at the main library desk. They will be held until May 22nd." :"safe",
    "Your flight confirmation: UA823 departing SFO 10:45AM arriving JFK 7:15PM on June 5th. Check-in opens 24hrs before departure." :"safe",
    "Hi team, I've uploaded the project files to our shared drive. Please review the documentation before Friday's meeting." :"safe",
    "Your prescription for Amoxicillin is ready for pickup at Walgreens on Main Street. Pharmacy hours: 9am-9pm." :"safe",
    "This is a reminder that your dentist appointment is scheduled for tomorrow at 3:30pm with Dr. Martinez." :"safe",
    "Hello participants, The webinar 'Professional Development in Tech Industries' will begin tomorrow at 1pm EST. Link to join was sent in a previous email." :"safe",
    "Your energy bill is now available. Amount due: $78.45. Due date: May 15. Log in to your account to view usage details." :"safe",
    "The office will be closed on Monday, May 29th in observance of Memorial Day. Regular hours will resume on Tuesday." :"safe",
    "Thank you for your donation to Red Cross Disaster Relief. Your contribution of $50 will help families affected by recent flooding." :"safe",
    "Your car service is scheduled for tomorrow at 9:00 AM at Joe's Auto Shop. Please bring your vehicle registration." :"safe",
    "Hi Jessica, I've reviewed your proposal and have some suggestions. Can we meet tomorrow afternoon to discuss?" :"safe",
    "The building will undergo maintenance this weekend. Water will be shut off from 10am-2pm on Saturday." :"safe",
    "Your tax documents for 2023 are now available in your online account. Please access them by April 15 for filing." :"safe",
    "Hello participants, thank you for attending yesterday's workshop. As promised, here are the slides and additional resources." :"safe",
    "Your library books are due in 3 days. Return or renew online at library.org to avoid late fees." :"safe",
    "This is a confirmation that your vacation time request (June 10-15) has been approved. Enjoy your time off!" :"safe",
    "Hi Ryan, could you cover my shift on Friday evening? I have a family emergency. I'll be happy to take your Sunday shift in return." :"safe",
    "Your monthly account statement is ready. No unusual activity detected. Log in to view details." :"safe",
    "The school board meeting has been rescheduled to next Thursday at 7pm in the auditorium. Public comments welcome." :"safe",
    "Just checking if you received the contract I sent last week? We need your signature by Friday to proceed." :"safe",
    "Your order from Fresh Groceries will be delivered today between 2-4pm. Please ensure someone is available to receive it." :"safe",
    "Congratulations on your work anniversary! It's been 5 years since you joined our team, and we appreciate your contributions." :"safe",
    "This is a friendly reminder that rent is due on the 1st of the month. You can pay online or drop a check at the office." :"safe",
    "The gym will be closed from 9pm-5am tonight for routine maintenance. We apologize for any inconvenience." :"safe",
    "Dear valued customer, thank you for your recent purchase. Please allow 3-5 business days for delivery." :"safe",
    "Your pet's annual vaccination is due this month. Please call our office to schedule an appointment." :"safe",
    "Team update: We've successfully launched the new website. Thank you all for your hard work on this project." :"safe",
    "Your subscription to The New York Times will renew automatically on June 1. Your card ending in 4832 will be charged $15.99." :"safe",
    "The neighborhood watch meeting is scheduled for Wednesday at 7pm at the community center. New members welcome." :"safe",
    "Thank you for registering for our upcoming conference. Check-in begins at 8:30am on May 20th." :"safe",
    "Your insurance policy is up for renewal next month. No action is needed; it will renew automatically." :"safe",
    "Hello, this is a reminder about our book club meeting tomorrow at 7pm. We'll be discussing 'The Great Gatsby'." :"safe",
    "Your appointment with Dr. Johnson has been confirmed for Tuesday at 10:30am. Please arrive 15 minutes early." :"safe",
    "The company holiday party will be held on December 18th at The Grand Hotel. Please RSVP by December 1st." :"safe",
    "Your child's school will have an early dismissal at 12:30pm on Friday due to teacher development." :"safe",
    "This is to confirm your reservation at Seaside Restaurant for Saturday at 7:30pm for a party of 4." :"safe",
    "Thank you for your payment of $1,250 for Invoice #12345. Your account is now current." :"safe",
    "The building fire alarm testing will take place on Tuesday morning between 10-11am. No evacuation necessary." :"safe",
    "Your membership to the fitness center has been renewed. Your new card is available at the front desk." :"safe",
    "Just wanted to thank you for your referral of John Smith. We're excited to have him join our team next month." :"safe",
    "Your water bill is slightly higher than usual this month. We've included tips for conservation in this email." :"safe",
    "Hi Dave, do you have the quarterly sales figures? I need to include them in my presentation for tomorrow." :"safe",

    # MALICIOUS
    "URGENT: Your account has been compromised! Verify your identity immediately: http://banking-secure-verify.com": "malicious",
    "Your Amazon order #39572 has been processed. Click here to track your package: http://amaz0n-tracking-secure.net": "malicious",
    "WARNING: Your PayPal account will be suspended in 24 hours. Verify your information: http://payp@l-secure.com": "malicious",
    "You've won a $1000 Walmart gift card! Claim now: http://free-walmart-gifts.com. Offer expires in 24 hours!": "malicious",
    "Your Netflix subscription payment failed. Update your billing information immediately: http://netflix-accounts-billing.com": "malicious",
    "IRS TAX REFUND: You are eligible for an additional $4,829.00 refund. Submit your details: http://irs-refund-gov.org": "malicious",
    "Your Apple ID was used to sign in on a new device. If this wasn't you, recover your account: http://apple-id-verify.net": "malicious",
    "Bank of America: Your online access has been temporarily disabled. Restore access: http://bofa-secure-login.com": "malicious",
    "ATTENTION: Your Social Security Number has been suspended due to suspicious activity. Call immediately: 1-888-555-1234": "malicious",
    "Microsoft Security Alert: Your email account shows unusual sign-in activity. Verify your identity: http://microsoft-verify.net": "malicious",
    "Your package could not be delivered due to incorrect address. Reschedule delivery: http://usps-delivery-reschedule.com": "malicious",
    "Your credit card has been charged $499 for iPhone 15 purchase. If this wasn't you, dispute here: http://billing-dispute-form.com": "malicious",
    "FINAL NOTICE: Your vehicle warranty is about to expire. Extend coverage at 50% discount: http://auto-warranty-extension.com": "malicious",
    "Facebook Security: Your account was recently logged into from an unrecognized location. Verify it's you: http://facebook-secure-login.net": "malicious",
    "You have (7) unread important messages from your bank. Access them here: http://secure-messages-bank.com": "malicious",
    "Costco Customer Survey: Answer 5 questions and receive a $50 gift card! http://costco-customer-rewards.com": "malicious",
    "URGENT: Unauthorized transaction of $854.21 detected on your account. Dispute now: http://fraud-alert-center.com": "malicious",
    "Your FedEx package #85742 is waiting for delivery confirmation. Schedule delivery: http://fedex-delivery-schedule.net": "malicious",
    "LinkedIn Security: Someone tried to access your account. Reset your password: http://linkedin-account-secure.com": "malicious",
    "Your electricity bill is overdue! Pay now to avoid service disconnection: http://utility-bill-payment.org": "malicious",
    "IMPORTANT: Your health insurance policy requires immediate verification. Complete here: http://health-benefits-verify.com": "malicious",
    "Your Google Drive account is reaching storage limit. Upgrade now at 70% discount: http://google-storage-special.com": "malicious",
    "Venmo Security Alert: Suspicious transaction detected. Verify your account: http://venmo-secure-verify.com": "malicious",
    "Your computer has been infected with a virus! Download antivirus protection: http://virus-protection-download.net": "malicious",
    "DocuSign: You have a document waiting for signature from Wells Fargo Bank. Sign here: http://docusign-secure-documents.com": "malicious",
    "Your child's school has an emergency. Contact administration immediately: http://school-emergency-notification.org": "malicious",
    "Chase Bank: Your account access has been limited due to multiple failed login attempts. Verify identity: http://chase-account-verify.com": "malicious",
    "LAST CHANCE: Your unclaimed tax refund of $3,247.89 expires today. Claim now: http://tax-refund-claims.com": "malicious",
    "COVID-19 Relief Payment: You qualify for additional $2,400 payment. Confirm eligibility: http://covid-relief-funds.org": "malicious",
    "Instagram Security: Unusual login attempt detected. Verify it's you: http://instagram-verify-login.com": "malicious",
    "Your order from Walmart has been processed and charged to your card ending in ****. Dispute unauthorized charge: http://walmart-order-dispute.com": "malicious",
    "URGENT: Your Amazon Prime membership will be automatically renewed for $129.99. Cancel here: http://amazon-membership-cancel.net": "malicious",
    "Your UPS package contains an undeliverable item. Schedule inspection: http://ups-package-resolution.com": "malicious",
    "Coinbase Security Alert: Your account shows suspicious withdrawal attempt. Confirm identity: http://coinbase-security-check.com": "malicious",
    "IMPORTANT: Your insurance claim #45873 requires additional documentation. Submit here: http://insurance-claims-center.org": "malicious",
    "Wells Fargo: New security measures require verification. Update your account: http://wellsfargo-secure-update.com": "malicious",
    "Your password for Microsoft Office 365 will expire in 24 hours. Reset now: http://office365-password-update.net": "malicious",
    "Unauthorized Netflix subscription charged to your account. Cancel payment: http://netflix-billing-cancel.com": "malicious",
    "Your flight reservation has been changed. Confirm new itinerary: http://airline-itinerary-confirm.com": "malicious",
    "Attention: Your home address verification failed. Update for continued delivery service: http://address-verification-center.org": "malicious",
    "Your AT&T account shows overdue balance of $237.45. Pay now to avoid service interruption: http://att-payment-urgent.com": "malicious",
    "iPhone 15 Pro Giveaway: You've been selected as a potential winner. Claim prize: http://apple-product-giveaway.net": "malicious",
    "ALERT: Your Direct Deposit information for payroll has been changed. Verify changes: http://payroll-verification.com": "malicious",
    "Important notice from IRS: Your tax return has discrepancies that require immediate attention: http://irs-tax-notice.org": "malicious",
    "Your Facebook account will be permanently deleted due to policy violations. Appeal here: http://facebook-appeal-form.com": "malicious",
    "Security Alert: Your Zelle payment of $750 is pending verification. Confirm transfer: http://zelle-transfer-verify.net": "malicious",
    "URGENT: Your child's school requires immediate updated emergency contact information: http://school-emergency-update.com": "malicious",
    "Department of Motor Vehicles: Your registration has discrepancies. Resolve here: http://dmv-registration-resolve.org": "malicious",
    "Your Disney+ subscription payment failed. Update payment method: http://disneyplus-billing-update.com": "malicious",
    "Your Social Security benefits require verification to continue payments. Verify here: http://ssa-benefits-verify.org": "malicious",
}
